import { Platform } from 'react-native';

const palette = {
  blue: '#007AFF',
  blueDark: '#0A84FF',
  blueLight: '#5AC8FA',
  orange: '#FF9500',
  orangeDark: '#FFB340',
  green: '#34C759',
  red: '#FF3B30',
  redDark: '#FF453A',
  gray1: '#8E8E93',
  gray2: '#AEAEB2',
  gray3: '#C7C7CC',
  gray4: '#D1D1D6',
  gray5: '#E5E5EA',
  gray6: '#F2F2F7',
  darkBg: '#0D0D0D',
  darkCard: '#1A1A2E',
  darkElevated: '#24243A',
  darkText: '#F5F5F7',
  darkSecondary: '#9E9E9E',
  darkBorder: '#2C2C35',
  lightBg: '#F2F2F6',
  lightCard: '#FFFFFF',
  lightText: '#1C1C1E',
  lightSecondary: '#8E8E93',
  lightBorder: '#D1D1D6',
};

export const Colors = {
  light: {
    text: palette.lightText,
    textSecondary: palette.lightSecondary,
    background: palette.lightBg,
    tint: palette.blue,
    icon: palette.gray1,
    tabIconDefault: palette.gray1,
    tabIconSelected: palette.blue,
    secondary: palette.blueLight,
    accent: palette.orange,
    success: palette.green,
    danger: palette.red,
    border: palette.lightBorder,
    card: palette.lightCard,
    cardSecondary: palette.gray6,
    lightGray: palette.gray6,
    elevated: '#FFFFFF',
    headerBg: palette.lightCard,
    tabBar: palette.lightCard,
  },
  dark: {
    text: palette.darkText,
    textSecondary: palette.darkSecondary,
    background: palette.darkBg,
    tint: palette.blueDark,
    icon: palette.gray1,
    tabIconDefault: palette.gray1,
    tabIconSelected: palette.blueDark,
    secondary: palette.blueLight,
    accent: palette.orangeDark,
    success: palette.green,
    danger: palette.redDark,
    border: palette.darkBorder,
    card: palette.darkCard,
    cardSecondary: palette.darkElevated,
    lightGray: '#2C2C2E',
    elevated: palette.darkElevated,
    headerBg: palette.darkCard,
    tabBar: palette.darkCard,
  },
};

export const StateColors: Record<number, { light: string; dark: string }> = {
  1: { light: '#FFB74D', dark: '#FFA500' },
  2: { light: '#42A5F5', dark: '#5AC8FA' },
  3: { light: '#FF7043', dark: '#FF8A65' },
  4: { light: '#EF5350', dark: '#E57373' },
  5: { light: '#AB47BC', dark: '#CE93D8' },
  6: { light: '#66BB6A', dark: '#34C759' },
};

export const Fonts = Platform.select({
  ios: {
    sans: 'system-ui',
    serif: 'ui-serif',
    rounded: 'ui-rounded',
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
